apiVersion: v1
kind: Secret
metadata:
  name: sgr-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "sgr.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: "{{ .Release.Name }}-postgresql"
  DB_PORT: "5432"
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}

  REDIS_HOST: "{{ .Release.Name }}-redis-master"
  REDIS_PORT: "6379"

  API_SECRET_KEY: {{ .Values.secrets.apiSecretKey | quote }}
  ENCRYPTION_MASTER_KEY: {{ .Values.secrets.encryptionKey | quote }}

  MONITORING_SENTRY_DSN: {{ .Values.secrets.sentryDsn | quote }}
  MONITORING_TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramToken | quote }}
  MONITORING_TELEGRAM_CHAT_ID: {{ .Values.secrets.telegramChatId | quote }}
