"""
SGR Prometheus Metrics
======================
Alle System-Metriken für Prometheus + Grafana.

Metric-Kategorien:
    Trading:     Orders, Fills, Slippage, PnL
    Risk:        VaR, Drawdown, Portfolio Heat, Kill Switch
    Market Data: Latenz, Gap-Rate, Feature-Berechnung
    Exchange:    Latenz, Error-Rate, Rate-Limit-Hits
    System:      CPU, Memory (via process_collector)

Naming Convention: sgr_{modul}_{metrik}_{einheit}
    sgr_orders_submitted_total
    sgr_risk_drawdown_pct
    sgr_exchange_latency_ms_bucket

Cardinality-Regel:
    Keine User-IDs oder Order-IDs als Labels (→ Cardinality-Explosion).
    Labels: exchange, symbol (top-5), trading_mode, strategy
"""

from __future__ import annotations

from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    Info,
)

# ---------------------------------------------------------------------------
# System Info
# ---------------------------------------------------------------------------

sgr_info = Info(
    "sgr",
    "SGR system information",
)

# ---------------------------------------------------------------------------
# Trading Metrics
# ---------------------------------------------------------------------------

orders_submitted = Counter(
    "sgr_orders_submitted_total",
    "Total orders submitted to exchange",
    ["exchange", "trading_mode", "order_type"],
)

orders_filled = Counter(
    "sgr_orders_filled_total",
    "Total orders successfully filled",
    ["exchange", "trading_mode"],
)

orders_rejected = Counter(
    "sgr_orders_rejected_total",
    "Total orders rejected (by risk engine or exchange)",
    ["reason_category", "trading_mode"],
)

order_fill_latency = Histogram(
    "sgr_order_fill_latency_seconds",
    "Time from order submission to fill confirmation",
    ["exchange", "order_type"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
)

slippage_pct = Histogram(
    "sgr_order_slippage_pct",
    "Slippage as percentage of expected fill price",
    ["exchange", "side"],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
)

signals_generated = Counter(
    "sgr_signals_generated_total",
    "Signals generated by strategy engine",
    ["strategy", "direction", "regime"],
)

signals_approved = Counter(
    "sgr_signals_approved_total",
    "Signals approved by risk engine",
    ["strategy", "trading_mode"],
)

signals_rejected_risk = Counter(
    "sgr_signals_rejected_risk_total",
    "Signals rejected by risk engine",
    ["reason_category", "trading_mode"],
)

# ---------------------------------------------------------------------------
# Portfolio Metrics
# ---------------------------------------------------------------------------

portfolio_value = Gauge(
    "sgr_portfolio_value_usdt",
    "Total portfolio value in USDT",
    ["trading_mode"],
)

portfolio_pnl_daily = Gauge(
    "sgr_portfolio_pnl_daily_pct",
    "Daily PnL as percentage",
    ["trading_mode"],
)

open_positions = Gauge(
    "sgr_open_positions_count",
    "Number of currently open positions",
    ["trading_mode"],
)

realized_pnl_total = Counter(
    "sgr_realized_pnl_usdt_total",
    "Total realized PnL in USDT (cumulative)",
    ["strategy", "trading_mode"],
)

# ---------------------------------------------------------------------------
# Risk Metrics
# ---------------------------------------------------------------------------

drawdown_pct = Gauge(
    "sgr_risk_drawdown_pct",
    "Current drawdown from peak as percentage",
    ["trading_mode"],
)

var_95 = Gauge(
    "sgr_risk_var_95_pct",
    "Value at Risk 95% as percentage",
    ["trading_mode"],
)

portfolio_heat = Gauge(
    "sgr_risk_portfolio_heat_pct",
    "Portfolio heat (sum of risk units) as percentage",
    ["trading_mode"],
)

kill_switch_triggered = Counter(
    "sgr_risk_kill_switch_triggered_total",
    "Total Kill Switch trigger events",
    ["trading_mode", "reason_category"],
)

kill_switch_active = Gauge(
    "sgr_risk_kill_switch_active",
    "1 if kill switch is currently active, 0 otherwise",
    ["trading_mode"],
)

# ---------------------------------------------------------------------------
# Exchange Metrics
# ---------------------------------------------------------------------------

exchange_request_latency = Histogram(
    "sgr_exchange_request_latency_ms",
    "Exchange API request latency in milliseconds",
    ["exchange", "endpoint"],
    buckets=[10, 50, 100, 200, 500, 1000, 2000, 5000],
)

exchange_errors = Counter(
    "sgr_exchange_errors_total",
    "Total exchange API errors",
    ["exchange", "error_type"],
)

exchange_rate_limit_hits = Counter(
    "sgr_exchange_rate_limit_hits_total",
    "Total rate limit events",
    ["exchange"],
)

# ---------------------------------------------------------------------------
# Market Data Metrics
# ---------------------------------------------------------------------------

candles_ingested = Counter(
    "sgr_market_data_candles_ingested_total",
    "Total candles ingested from exchanges",
    ["exchange", "symbol", "timeframe"],
)

data_gaps_detected = Counter(
    "sgr_market_data_gaps_detected_total",
    "Missing candle gaps detected",
    ["exchange", "symbol", "timeframe"],
)

feature_computation_duration = Histogram(
    "sgr_feature_computation_duration_seconds",
    "Time to compute feature set from candles",
    ["symbol", "timeframe"],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
)

feature_store_latency = Histogram(
    "sgr_feature_store_latency_ms",
    "Redis feature store read/write latency",
    ["operation"],
    buckets=[0.1, 0.5, 1, 2, 5, 10, 50],
)

# ---------------------------------------------------------------------------
# Strategy Metrics
# ---------------------------------------------------------------------------

strategy_active_count = Gauge(
    "sgr_strategy_active_count",
    "Number of currently active strategies",
)

strategy_sharpe = Gauge(
    "sgr_strategy_sharpe_ratio",
    "Rolling Sharpe Ratio per strategy",
    ["strategy", "trading_mode"],
)

strategy_hit_rate = Gauge(
    "sgr_strategy_hit_rate_pct",
    "Hit rate (win rate) per strategy as percentage",
    ["strategy", "trading_mode"],
)

# ---------------------------------------------------------------------------
# API Metrics
# ---------------------------------------------------------------------------

api_requests = Counter(
    "sgr_api_requests_total",
    "Total API requests",
    ["method", "path", "status_code"],
)

api_latency = Histogram(
    "sgr_api_request_duration_seconds",
    "API request duration in seconds",
    ["method", "path"],
    buckets=[0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5],
)

ws_connections = Gauge(
    "sgr_websocket_connections_active",
    "Number of active WebSocket connections",
    ["stream"],
)


# ---------------------------------------------------------------------------
# Collector Helper
# ---------------------------------------------------------------------------


def update_system_info(version: str, environment: str, trading_mode: str) -> None:
    """Setzt statische System-Info Metriken einmalig beim Start."""
    sgr_info.info(
        {
            "version": version,
            "environment": environment,
            "trading_mode": trading_mode,
        }
    )


def record_kill_switch_trigger(trading_mode: str, reason: str) -> None:
    """Kategorisiert Kill-Switch-Grund für Prometheus."""
    if "drawdown" in reason.lower():
        category = "drawdown"
    elif "daily_loss" in reason.lower() or "daily loss" in reason.lower():
        category = "daily_loss"
    elif "manual" in reason.lower():
        category = "manual"
    elif "connection" in reason.lower() or "exchange" in reason.lower():
        category = "exchange_error"
    else:
        category = "other"

    kill_switch_triggered.labels(
        trading_mode=trading_mode,
        reason_category=category,
    ).inc()
